core/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static 


from django.contrib.sitemaps.views import sitemap
from core.sitemaps import HomeViewSitemap


sitemaps = {
    'home': HomeViewSitemap,
}



urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('home.urls', namespace='home')),
    
    re_path(r'^robots\.txt$', serve, {
        'document_root': settings.BASE_DIR,
        'path': 'robots.txt',
    }),

    path(
        'sitemap.xml',
        sitemap,
        {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap',
    ),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import *


app_name = 'home'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('save-request/', SaveRequestView.as_view(), name='save-request'),
]

home/models.py
from django.db import models


class CompanyInfo(models.Model):
    phone = models.CharField('Телефон', max_length=20)
    address = models.CharField('Адрес', max_length=255)
    work_time = models.CharField('Режим работы', max_length=255)
    email = models.EmailField('Email', max_length=255) 
    whatsapp = models.CharField('Whatsapp', max_length=255)
    telegram = models.CharField('Telegram', max_length=255)
    about_us = models.TextField('О нас')
    why_it_is_cheaper_to_repair = models.TextField('Почему выгоднее чинить')

    def __str__(self):
        return 'Информация о компании'

    class Meta:
        verbose_name = 'Информация о компании'
        verbose_name_plural = 'Информация о компании'

    @classmethod
    def get_instance(cls) -> "CompanyInfo":
        instance, created = cls.objects.get_or_create(id=1)
        return instance


    def save(self, *args, **kwargs):
        if self.__class__.objects.count():
            self.pk = self.__class__.objects.first().pk
        super().save(*args, **kwargs)


class CompanyStat(models.Model):
    number = models.CharField('Метрика', max_length=255)
    label = models.CharField('Подпись', max_length=255) 
    small_label = models.CharField('Подпись снизу', max_length=255)

    def __str__(self):
        return f'{self.number} {self.label} {self.small_label}'

    class Meta:
        verbose_name = 'Статистика'
        verbose_name_plural = 'Статистика'


class Service(models.Model):
    name = models.CharField('Название', max_length=255)
    image = models.ImageField('Изображение', upload_to='services/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Услуга'
        verbose_name_plural = 'Услуги'



class Work(models.Model):
    name = models.CharField('Название', max_length=255)
    image = models.ImageField('Изображение', upload_to='works/')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Работа'
        verbose_name_plural = 'Работы'


class Request(models.Model):
    name = models.CharField('Имя', max_length=255)
    phone = models.CharField('Телефон', max_length=18)

    def __str__(self):
        return f'{self.name} {self.phone}'

    class Meta:
        verbose_name = 'Заявка'
        verbose_name_plural = 'Заявки'



class PersonalDataPolicy(models.Model):
    file = models.FileField('Файл', upload_to='personal_data_policy/', null=True, blank=True)

    class Meta:
        verbose_name = 'Обработка персональных данных'
        verbose_name_plural = 'Обработка персональных данных'

    def save(self, *args, **kwargs):
        if self.__class__.objects.count():
            self.pk = self.__class__.objects.first().pk
        super().save(*args, **kwargs)

    @classmethod 
    def get_instance(cls) -> "PersonalDataPolicy":
        instance, created = cls.objects.get_or_create(id=1)
        return instance

    def __str__(self) -> str:
        return 'Обработка персональных данных'


class PrivacyPolicy(models.Model): 
    file = models.FileField('Файл', upload_to='privacy_policy/', null=True, blank=True)

    class Meta: 
        verbose_name = 'Политика конфиденциальности'
        verbose_name_plural = 'Политика конфиденциальности'

    def save(self, *args, **kwargs):
        if self.__class__.objects.count():
            self.pk = self.__class__.objects.first().pk
        super().save(*args, **kwargs)

    @classmethod
    def get_instance(cls) -> "PrivacyPolicy":
        instance, created = cls.objects.get_or_create(id=1)
        return instance
    
    def __str__(self) -> str: 
        return 'Политика конфиденциальности'

home/views.py
from django.shortcuts import render
from django.views import View 
from .models import (
    CompanyInfo, 
    Service, 
    Work, 
    CompanyStat, 
    Request, 
    PrivacyPolicy, PersonalDataPolicy
)
import requests
from django.http import JsonResponse


class HomeView(View): 
    template_name = 'home/home.html'

    def get(self, request): 
        company_info = CompanyInfo.get_instance() 
        services = Service.objects.all()
        company_stats = CompanyStat.objects.all()
        works = Work.objects.all()
        privacy_policy = PrivacyPolicy.get_instance()
        personal_data_policy = PersonalDataPolicy.get_instance()
        context = {
            'company_info': company_info,
            'services': services,
            'works': works,
            'company_stats': company_stats,
            'privacy_policy': privacy_policy,
            'personal_data_policy': personal_data_policy,
        }
        return render(request, self.template_name, context)


class SaveRequestView(View):
    def post(self, request):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        Request.objects.create(name=name, phone=phone)

        recipient = 'mr.energia25@mail.ru'
        ip = '82.202.128.97'
        url = 'https://sendemail.space/send-email/'
        data = {
            'recipient': recipient, 
            'subject': 'Новая заявка с сайта', 
            'content': f'Имя: {name}\nТелефон: {phone}',
            'ip': ip,
        }
        response = requests.post(url, data=data) 

        return JsonResponse({'success': True})

home/templates/home/home.html
{% extends 'base.html' %}
{% load static %}
{% load phone_filters %}

{% block title %}
Ремонт электрооборудования и перемотка электродвигателей в Уссурйиске и Приморском крае
{% endblock title %}
{% block meta_title %}
Ремонт электрооборудования и перемотка электродвигателей в Уссурйиске и Приморском крае
{% endblock meta_title %}
{% block description %}
Ремонт и перемотка электродвигателей любой мощности, а также другого оборудования в Уссурийске и Приморье
{% endblock description %}
{% block meta_description %}
Ремонт и перемотка электродвигателей любой мощности, а также другого оборудования в Уссурийске и Приморье
{% endblock meta_description %}

{% block content %}
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<section class="home-section">
    <div class="container">
        <div class="home-content">
            <div class="upper">
                <h1>Ремонт, перемотка электродвигателей и оборудования</h1>
                <p>Ремонт электродвигателей и оборудования - <br> быстро, качественно, надежно</p>
            </div>
            <div class="medium">
                <a href="#map-section" class="home-request-button">Оставить заявку</a>
                <a href="#map-section" class="home-calculation-button">Получить расчет</a>
            </div>
            <img class="home-background" src="{% static 'images/main-bg.png' %}" alt="">
            <div class="lower">
                {% for stat in company_stats %}
                    <div class="stat">
                        <p><span>{{ stat.number }} </span> {{ stat.label }}</p>
                        <small>{{ stat.small_label }}</small>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</section>
<section id="services-section" class="services-section container">
    <h2 class="x-container">Услуги по ремонту оборудования</h2>
    <div class="services-swiper swiper">
        <div class="swiper-wrapper services-cards">
            {% for service in services %}
                <div class="service-card swiper-slide">
                    <img class="service-img" src="{{ service.image.url }}" alt="">
                    <p>{{ service.name }}</p>
                    <a href="#map-section" class="button">
                        <img src="{% static 'images/arrow.svg' %}" alt="">
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

<section class="stages-section container">
    <div class="stages-card">
        <h2>Этапы работы</h2>
        <div class="stages-row">
            <div class="stage">
                <div class="number">1</div>
                <div class="label">Оставить заявку</div>
            </div>
            <img class="only-desktop" src="{% static 'images/stage-arrow-small.svg' %}" alt="">
            <img class="only-mobile" src="{% static 'images/triangle-arrow-down.svg' %}" alt="">
            <div class="stage">
                <div class="number">2</div>
                <div class="label">Определение неисправностей двигателя</div>
            </div>
            <img class="only-desktop" src="{% static 'images/stage-arrow-small.svg' %}" alt="">
            <img class="only-mobile" src="{% static 'images/triangle-arrow-down.svg' %}" alt="">
            <div class="stage">
                <div class="number">3</div>
                <div class="label">Проверка и восстановление посадочных мест</div>
            </div>
            <img class="only-desktop" src="{% static 'images/stage-arrow-small.svg' %}" alt="">
            <img class="only-mobile" src="{% static 'images/triangle-arrow-down.svg' %}" alt="">
            <div class="stage">
                <div class="number">4</div>
                <div class="label">Извлечение старой обмотки</div>
            </div>
            <img class="only-mobile" src="{% static 'images/triangle-arrow-down.svg' %}" alt="">
        </div>
        <div class="stages-row">
            <div class="stage">
                <div class="number">5</div>
                <div class="label">Укладка новой обмотки</div>
            </div>
            <img class="only-desktop" src="{% static 'images/stage-arrow-medium.svg' %}" alt="">
            <img class="only-mobile" src="{% static 'images/triangle-arrow-down.svg' %}" alt="">
            <div class="stage">
                <div class="number">6</div>
                <div class="label">Сборка схемы</div>
            </div>
            <img class="only-desktop" src="{% static 'images/stage-arrow-big.svg' %}" alt="">
            <img class="only-mobile" src="{% static 'images/triangle-arrow-down.svg' %}" alt="">
            <div class="stage">
                <div class="number">7</div>
                <div class="label">Пропитка и сушка</div>
            </div>
            <img class="only-desktop" src="{% static 'images/stage-arrow-big.svg' %}" alt="">
            <img class="only-mobile" src="{% static 'images/triangle-arrow-down.svg' %}" alt="">
            <div class="stage">
                <div class="number">8</div>
                <div class="label">Сбор и запуск двигателя</div>
            </div>
        </div>
        <div class="bottom">
            <p>На всех этапах ремонта вы можете рассчитывать на нашу поддержку и экспертное сопровождение. Вместе мы справимся с любой неисправностью и вернем ваш электродвигатель в строй!</p>
            <a href="#map-section" class="stages-request-button">Оставить заявку</a>
        </div>
    </div>
</section>

<section class="about-section container">
    <div class="about-card">
        <div class="info">
            <h2>Почему чинить <br> выгоднее</h2>
            <p>{{ company_info.why_it_is_cheaper_to_repair }}</p>
        </div>
        <div class="divider"></div>
        <div class="company">
            <h2>О нас</h2>
            <p>{{ company_info.about_us }}</p>
        </div>
    </div>
    <div class="info-panel">
        <div class="info-panel-container">
            <div class="info-panel-inner">
                <div class="info-obj">
                    <img src="{% static 'images/info-obj-1.svg' %}" alt="">
                    <p>Гарантия на работу</p>
                </div>
                <div class="info-obj">
                    <img src="{% static 'images/info-obj-2.svg' %}" alt="">
                    <p>Современное оборудование</p>
                </div>
                <div class="info-obj">
                    <img src="{% static 'images/info-obj-3.svg' %}" alt="">
                    <p>Быстрые сроки</p>
                </div>
                <div class="info-obj">
                    <img src="{% static 'images/info-obj-4.svg' %}" alt="">
                    <p>Опытные специалисты</p>
                </div>
            </div>
        </div>
    </div>
</section>


<section id="works-section" class="works-section container">
    <h2 class="x-container">Наши работы</h2>
    <div class="works-navigation">
        <div class="works-button-prev">
            <img src="{% static 'images/slider-arrow-left.svg' %}" alt="Предыдущий">
        </div>
        <div class="works-button-next">
            <img src="{% static 'images/slider-arrow-right.svg' %}" alt="Следующий">
        </div>
    </div>
    <div class="works swiper">
        <div class="swiper-wrapper">
            {% for work in works %}
                <div class="work-card swiper-slide">
                    <img src="{{ work.image.url }}" alt="">
                    <div class="bottom">
                        <p class="label">Тип работ:</p>
                        <p class="text">{{ work.name }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</section>

<section class="map-section" id="map-section">
    <div class="container">
        <div id="map">
            <div class="map-info">
                <p class="heading">Контакты</p>
                <div class="map-info-content">
                    <div>
                        <small>Телефон</small>
                        
                        <a target="_blank" href="tel:+{{ company_info.phone|phone_link }}">{{ company_info.phone }}</a>
                    </div>
                    <div>
                        <small>Адрес</small>
                        <a target="_blank">{{ company_info.address }}</a>
                    </div>
                    <div>
                        <small>Режим работы:</small>
                        <p>{{ company_info.work_time }}</p>
                    </div>
                </div>
            </div>
        </div>
        <form action="" class="request-form" id="request-form">
            {% csrf_token %}
            <div class="upper">
                <p class="heading">Оставьте заявку</p>
                <small>Мы свяжемся с вами в ближайшее время, чтобы ответить на все ваши вопросы</small>
            </div>
            <div class="inputs">
                <input type="text" name="name" required placeholder="Имя">
                <input type="tel" name="phone" maxlength="18" required placeholder="Телефон">
                <button class="home-request-button">Оставить заявку</button>
            </div>
        </form>
    </div>
</section>

{% endblock %}


{% block script %}
<!-- Работы -->
<script defer>
    const worksSlider = new Swiper('.works.swiper', {
        slidesPerView: 4,
        spaceBetween: 30,
        navigation: {
            nextEl: '.works-navigation .works-button-next',
            prevEl: '.works-navigation .works-button-prev',
        }, 
        spaceBetween: 20,
        breakpoints: {
            1200: {
                slidesPerView: 4,
                slidesOffsetBefore: 0,
                slidesOffsetAfter: 0,
            },
            900: {
                slidesPerView: 3,
            },
            600: {
                slidesPerView: 2,
            },
            0: {
                slidesPerView: 1.4,
                slidesOffsetBefore: 16,
                slidesOffsetAfter: 16,
            }
        }
    });
</script>


<script>
    var myMap;
    ymaps.ready((function() {
        myMap = new ymaps.Map("map", {
            center: [43.833199, 131.937147],
            zoom: 18,
            controls: []
        });
        var o = new ymaps.control.ZoomControl({
            options: {
                position: {
                    right: 10,
                    top: 50
                },
                size: "small"
            }
        });
        myMap.controls.add(o), myMap.behaviors.disable("scrollZoom");
        var a = new ymaps.Placemark([43.799217, 131.947627], {
            hintContent: "Уссурийск, ул.Фадеева 12, стр. 3",
            balloonContent: "Уссурийск, ул.Фадеева 12, стр. 3"
        }, {
            iconLayout: "default#image", 
            iconImageHref: "/static/images/pin.svg",
            iconImageSize: [30, 42],
            iconImageOffset: [-15, -42]
        });
        myMap.geoObjects.add(a)
    }))
    
</script>

<script defer>
    const requestForm = document.getElementById('request-form')
    requestForm.addEventListener('submit', (e) => {
        e.preventDefault()
        const formData = new FormData(requestForm)
        
        axios.post('/save-request/', formData)
            .then(response => {
                requestForm.reset();

            })
            .catch(error => {
                console.error(error);
            });
        })
</script>

<!-- Услуги -->
<script defer>
    function isMobile() {
        return window.innerWidth < 990;
    }

    if (isMobile()) {
        const servicesSlider = new Swiper('.services-swiper.swiper', {
            slidesPerView: 1,
            spaceBetween: 30,
            slidesOffsetBefore: 0,
            slidesOffsetAfter: 0,
            breakpoints: {
                1200: {
                    slidesPerView: 4,
                    slidesOffsetBefore: 0,
                    slidesOffsetAfter: 0,
                },
                900: {
                    slidesPerView: 3,
                    slidesOffsetBefore: 32,
                    slidesOffsetAfter: 16,
                },
                600: {
                    slidesPerView: 2,
                },
                0: {
                    slidesPerView: 1.4,
                    slidesOffsetBefore: 32,
                    slidesOffsetAfter: 16,
                }
            }, 
        });
    }
</script>

<script defer>
    const mobileNavLinks = document.querySelectorAll('.burger-menu-inner a');
    mobileNavLinks.forEach(link => {
        link.addEventListener('click', () => {
            burgerMenu.classList.remove('active');
        });
    });
</script>
{% endblock %}

<style>
.services-swiper {
    position: relative;
    padding-bottom: 30px;
}
.services-swiper-button-prev,
.services-swiper-button-next {
    position: absolute;
    top: 50%;
    z-index: 10;
    width: 40px;
    height: 40px;
    background: none;
    border: none;
    cursor: pointer;
    transform: translateY(-50%);
    display: flex;
    align-items: center;
    justify-content: center;
}
.services-swiper-button-prev {
    left: -20px;
}
.services-swiper-button-next {
    right: -20px;
}
@media (max-width: 900px) {
    .services-swiper-button-prev {
        left: 0;
    }
    .services-swiper-button-next {
        right: 0;
    }
}
</style>

templates/base.html
{% load static %} 
{% load phone_filters %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Google fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&display=swap"
        rel="stylesheet">

    <!-- Local files -->
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/header.js' %}"></script>

    <!-- Libraries -->
    <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->
    <script src="{% static 'js/imask/Imask.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />

    <!-- Logo -->
    <link rel=icon type=image/png sizes=16x16 href="{% static 'images/logo.svg' %}">

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
        (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
        m[i].l=1*new Date();
        for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
        k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
    
        ym(101628909, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true
        });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/101628909" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->

    
    <title>{% block title %}{% endblock title %}</title>
    <meta name=description content="{% block description %}{% endblock %}">
    <meta property=og:title content="{% block meta_title %}{% endblock %}">
    <meta property=og:description content="{% block meta_description %}{% endblock %}">
    
    {% block head %}
    {% endblock %}
</head>

<body>
    <header class="header">
        <div class="burger-menu">
            <div class="burger-menu-inner">
                <a href="#services-section">Услуги</a>
                <a href="#works-section">Кейсы</a>
                <a href="#map-section">Контакты</a>
            </div>
        </div>
        <div class="container">
            <div class="two-parts">
                <div class="left-part">
                    <a href="{% url 'home:home' %}"><img class="" src="{% static 'images/logo.svg' %}" alt=""></a>
                    <div class="nav-menu">
                        
                        <a href="#services-section">Услуги</a>
                        <a href="#works-section">Кейсы</a>
                        <a href="#map-section">Контакты</a>
                    </div>
                </div>
                <div class="right-part">
                    <div class="contacts">
                        <a class="phone" href="tel:{{ company_info.phone|phone_link }}">{{ company_info.phone }}</a>
                        <a target="_blank" href="{{ company_info.whatsapp }}"><img src="{% static 'images/whatsapp.svg' %}" alt=""></a>
                        <a target="_blank" href="{{ company_info.telegram }}"><img src="{% static 'images/telegram.svg' %}" alt=""></a>
                    </div>
                    <a href="#map-section" class="request-button">Оставить заявку</a>
                    <div class="burger-menu-button only-mobile flex">
                        <img src="{% static 'images/burger.svg' %}" alt="Меню">
                    </div>
                </div>
            </div>
        </div>
    </header>

    <main>
        {% block content %}
        
        {% endblock %}
    </main>

    <footer>
        <div class="container">
            <div class="upper">
                <div class="left-part">
                    <img class="" src="{% static 'images/logo.svg' %}" alt="">
                    <div class="nav-menu">
                        <a href="#services-section">Услуги</a>
                        <a href="#works-section">Кейсы</a>
                        <a href="#map-section">Контакты</a>
                    </div>
                </div>
                <div class="right-part">
                    <a class="email" href="mailto:{{ company_info.email }}">{{ company_info.email }}</a>
                    <div class="contacts">
                        <a class="phone" href="tel:{{ company_info.phone|phone_link }}">{{ company_info.phone }}</a>
                        <a target="_blank" href="{{ company_info.whatsapp }}"><img src="{% static 'images/whatsapp.svg' %}" alt=""></a>
                        <a target="_blank" href="{{ company_info.telegram }}"><img src="{% static 'images/telegram.svg' %}" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="divider"></div>
            <div class="lower">
                <p><a href="{{ privacy_policy.file.url }}">политика конфиденциальности</a> и <a href="{{ personal_data_policy.file.url }}">обработки персональных данных</a></p>
            </div>
        </div>
    </footer>
</body>

{% block script %}
{% endblock %}


<script defer>
// Маска
document.querySelectorAll('input[type="tel"]').forEach(input => {
    let phoneMask = IMask(input, { mask: "+{7} (000) 000-00-00" });

    function validatePhoneNumber() {
        let t = input.value.replace(/\D/g, "");
        return t.length < 11 ? (input.setCustomValidity("Необходимо минимум 11 цифр"), !1) : (input.setCustomValidity(""), !0);
    }

    input.addEventListener("input", validatePhoneNumber);
});
</script>


<script defer>
    const burgerMenuButton = document.querySelector('.burger-menu-button');
    const burgerMenu = document.querySelector('.burger-menu');

    burgerMenuButton.addEventListener('click', () => {
        burgerMenu.classList.toggle('active');
    }); 
</script>